version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-deepstream:*